"""Add Scans table

Revision ID: 076b9fa96466
Revises: 
Create Date: 2022-03-16 17:51:55.439032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '076b9fa96466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('orientation', mysql.INTEGER(display_width=1), nullable=True),
    sa.Column('license_number', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    # ### end Alembic commands ###
