"""Add Identities table

Revision ID: 15a56d039681
Revises: 1a069c14881a
Create Date: 2022-03-17 16:19:24.816311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15a56d039681'
down_revision = '1a069c14881a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('vip', sa.Integer(), nullable=False),
    sa.Column('ban', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identities')
    # ### end Alembic commands ###
