"""Add Scans table

Revision ID: 1a069c14881a
Revises: 
Create Date: 2022-03-17 16:17:35.782988

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1a069c14881a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orientation', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    # ### end Alembic commands ###
